<?php
/**
 * Copyright © 2015 Magenest. All rights reserved.
 * See COPYING.txt for license details.
 *
 *
 * Magenest_SmsMarketing extension
 * NOTICE OF LICENSE
 *
 * @category  Magenest
 * @package   Magenest_SmsMarketing
 * @author CanhND
 */
?>
<div class="actions actions-get-auth-token textmarketer">
    <div style="color: red" id="auth_token_result_textmarketer" class="message-validation hide"></div>
    <button  class="action-validate-get-auth-token-textmarketer" type="button"  id="<?php echo $block->getHtmlId() ?>">
        <span><?php /* @escapeNotVerified */ echo $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
</div>
<script>
    require(['jquery'], function(jQuery){
        jQuery('.action-validate-get-auth-token-textmarketer').click(function(){
            var username = jQuery('#smsmarketing_integration_textmarketer_username').val();
            var password = jQuery('#smsmarketing_integration_textmarketer_password').val();
            var number = jQuery('#smsmarketing_integration_textmarketer_number').val();
            var data = {
                username: username,
                password : password,
                number : number,
                form_key: FORM_KEY
            };
            var url = '<?php echo $block->getUrl('smsmarketing/system_config/check'); ?>//';
            jQuery.ajax({
                type: "POST",
                url: url,
                data: data,
                showLoader: true,
                success: function(response){
                    var result_token = jQuery('#auth_token_result_textmarketer');
                    var responseObj = JSON.parse(response);
                    console.log(responseObj);
                    if(responseObj.error == 1){
                        jQuery('#smsmarketing_textmarketer_auth_token').val(responseObj.description);
                        result_token.removeClass('hide').addClass('error');
                        result_token.html(responseObj.description);
                    }else{
                        jQuery('#smsmarketing_textmarketer_auth_token').val(responseObj.description);
                        jQuery('#<?php echo $block->getHtmlId() ?>').attr('disabled', 'disabled');
                        result_token.removeClass('hide').addClass('success');
                        result_token.html(responseObj.description);
                    }
                }
            });
        });
    });
</script>