<?php
/**
 * Created by Magenest
 * User: Luu Thanh Thuy
 * Date: 17/06/2016
 * Time: 10:03
 */
/** @var  $block \Magenest\SmsMarketing\Block\Account\Mobile */
$is_required_field = $block->isMobileRequired();
$mobileNumber = $block->getAccountInfo();
?>

<fieldset class="fieldset create account"
    <?php if ($is_required_field) { ?>
        data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
    <?php } ?>
>
    <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Additional Information') ?></span></legend><br>

    <div class="field mobile_numbers <?php if ($is_required_field) {
        ?> required <?php
    } ?>">
        <label for="mobile_numbers" class="label"><span><?php /* @escapeNotVerified */ echo __('Mobile Numbers') ?></span></label>
        <div class="control">
            <input type="text" name="mobile_numbers" id="mobile_numbers" title="<?php /* @escapeNotVerified */ echo __('Mobile Numbers') ?>"
                   class="input-text"  <?php  if ($is_required_field) {
                ?> data-validate="{required:true,'validate-greater-than-zero':true}" <?php
            } ?> autocomplete="off" value="<?php echo $block->getAccountInfo(); ?>" >
        </div>
    </div>
</fieldset>
